language: ruby

cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 3.0.0

gemfile:
  - gemfiles/Gemfile.ruby-1.9.x
  - gemfiles/Gemfile.ruby-2.0.x
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-4.2.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-6.1.x
  - gemfiles/Gemfile

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.16.1'

script:
  - bundle exec rake spec

before_script:
  - bundle exec rake phonelib:create_test_db

after_script:
  - CODECLIMATE_REPO_TOKEN=230dc861ec831b64dc4818a2002de07fbd2a413cc460385eb05958564eb70687 bundle exec codeclimate-test-reporter

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.ruby-2.0.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile.rails-6.1.x
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/Gemfile.rails-6.1.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.ruby-2.0.x
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.rails-6.1.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.ruby-2.0.x
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile.rails-6.1.x
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.ruby-2.0.x
    - rvm: 2.3.7
      gemfile: gemfiles/Gemfile.rails-6.1.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.ruby-2.0.x
    - rvm: 2.4.4
      gemfile: gemfiles/Gemfile.rails-6.1.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 2.5.1
      gemfile: gemfiles/Gemfile.ruby-2.0.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-3.1.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-3.2.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-4.0.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-4.1.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-4.2.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-5.0.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.rails-5.1.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.ruby-1.9.x
    - rvm: 3.0.0
      gemfile: gemfiles/Gemfile.ruby-2.0.x
